    <h2>Termo de uso</h2>
    <p>Este termo de uso é um acordo legal entre você e a empresa. Este termo de uso estabelece as condições gerais de uso do site e dos serviços oferecidos pela empresa. Ao acessar ou usar o site, você concorda em cumprir estes termos de uso. Se você não concordar com qualquer parte deste termo de uso, você não tem permissão para acessar ou usar o site ou os serviços.</p>
    <h2>Propriedade intelectual</h2>
    <p>O site e seus originais, recursos e funcionalidades são e permanecerão propriedade exclusiva da empresa e seus licenciadores. O site está protegido por leis de direitos autorais, marcas registradas e outras leis de propriedade intelectual do Brasil e de outros países. Nossos nomes e logotipos de empresas e todos os outros nomes, logotipos, produtos e serviços da empresa são marcas comerciais ou marcas registradas da empresa ou de nossos licenciadores. Você não tem permissão para usar essas marcas sem o consentimento prévio por escrito da empresa.</p>
    <h2>Links para outros sites</h2>
    <p>Nosso site pode conter links para sites de terceiros ou serviços que não são de propriedade ou controlados pela empresa. A empresa não tem controle e não assume nenhuma responsabilidade pelo conteúdo, políticas de privacidade ou práticas de quaisquer sites ou serviços de terceiros. Você reconhece e concorda que a empresa não será responsável, direta ou indiretamente, por qualquer dano ou perda causada ou alegadamente causada por ou em conexão com o uso ou confiança em qualquer conteúdo, bens ou serviços disponíveis em ou através de qualquer site ou serviço.</p>
    <h2>Alterações</h2>
    <p>Reservamos o direito, a nosso critério exclusivo, de modificar ou substituir estes termos de uso a qualquer momento. Se uma revisão for material, tentaremos fornecer pelo menos 30 dias de aviso prévio antes que quaisquer novos termos entrem em vigor. O que constitui uma alteração material será determinado a nosso exclusivo critério.</p>
    <h2>Contato</h2>
    <p>Se você tiver alguma dúvida sobre estes termos de uso, entre em contato conosco.</p>
